### PR TITLE
fix windows xrick patch use

### PR DESCRIPTION
**Pull request by AlwinEsch**

### CODE REVIEW

**Comment by garbear** [comment]
Nice. I assume you converted the patch to CRLF? How should we handle kodi-game-scripting for this change?

**Comment by AlwinEsch** [comment]
Maybe to have it as default on all Windows builds.

So that https://github.com/kodi-game/kodi-game-scripting/tree/master/templates/addon/depends/windows include `{{ game.name }}` too.

Think with patches still need added by hand? If yes can it then be added there as different to match Windows.

The `addon/depends/common/{{ game.name }}/windows-deps.txt.j2` can then also be removed as then on other folder as `deps.txt.j2`.

Most addons not need it but as this more easy to handle from script.

**Comment by AlwinEsch** [comment]
> Nice. I assume you converted the patch to CRLF?

Yes the above on patch with position references need there the CRLF too.

**Comment by garbear** [comment]
I modified kodi-game-scripting. Let's give this a try.

**Comment by garbear** [comment]
@AlwinEsch how did you generate the patch for CRLF files? retro8 and 3dengine need the same treatment.

**Pull request merged**
